apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 02-redis.yaml
  - 03-rbac.yaml
  - 04-gateway.yaml
  - 06-gpu-resourceclaim.yaml
  - 07-accel-timeslicer-daemonset.yaml
  - pvc.yaml
  - worker-pod-template.yaml
  - sampler-pod-template.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: open-rl-config
    literals:
      - BASE_MODEL="Qwen/Qwen2.5-0.5B"
      - ENABLE_GCP_TRACE="0"

images:
  - name: ghcr.io/gke-labs/open-rl/server
    newTag: latest
  - name: ghcr.io/gke-labs/open-rl/gateway
    newTag: latest
  - name: ghcr.io/gke-labs/open-rl/timeslicer
    newTag: latest

patches:
  - target:
      kind: DaemonSet
      name: open-rl-accel-timeslicer
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - "--listen-host"
          - "0.0.0.0"
          - "--port"
          - "9753"
          - "--backend"
          - "noop"
          - "--scheduling-policy"
          - "lrs"
