{
 "title": "Inference Gateway",
 "time": { "from": "2025-05-04T16:16:14.919Z", "to": "2025-05-04T16:51:40.407Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "# Inference Gateway Dashboard\n\nPlease see https://github.com/llm-d/llm-d-router/tree/main/pkg/epp/metrics for more details of underlying metrics used in the dashboard."
   }
  },
  {
   "title": "Inference Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average KV Cache Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(name) (llm_d_epp_average_kv_cache_utilization)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 4 },
     "targets": [
      {
       "expr": "sum by(name) (llm_d_epp_average_queue_size)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue Size Per Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by(name, model_server_endpoint, pod) (llm_d_epp_per_endpoint_queue_size)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Inference Objective",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "E2E Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_d_epp_request_duration_seconds_bucket{}[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(llm_d_epp_request_duration_seconds_bucket{}[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_d_epp_request_duration_seconds_bucket{}[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Request / s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by(model_name, target_model_name) (rate(llm_d_epp_request_total{}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Error / s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 13 },
     "targets": [
      {
       "expr": "(sum by(error_code, model_name, target_model_name) (rate(llm_d_epp_request_error_total[$__rate_interval]))) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_d_epp_request_size_bytes_bucket{}[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(llm_d_epp_request_size_bytes_bucket{}[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_d_epp_request_size_bytes_bucket{}[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Response Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 21 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(llm_d_epp_response_size_bytes_bucket{}[$__rate_interval])))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(llm_d_epp_response_size_bytes_bucket{}[$__rate_interval])))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(llm_d_epp_response_size_bytes_bucket{}[$__rate_interval])))",
       "legendFormat": "50%"
      }
     ]
    }
   ]
  }
 ]
}