//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorSpec) DeepCopyInto(out *AcceleratorSpec) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorSpec.
func (in *AcceleratorSpec) DeepCopy() *AcceleratorSpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenRLClaimGroup) DeepCopyInto(out *OpenRLClaimGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenRLClaimGroup.
func (in *OpenRLClaimGroup) DeepCopy() *OpenRLClaimGroup {
	if in == nil {
		return nil
	}
	out := new(OpenRLClaimGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenRLClaimGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenRLClaimGroupList) DeepCopyInto(out *OpenRLClaimGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenRLClaimGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenRLClaimGroupList.
func (in *OpenRLClaimGroupList) DeepCopy() *OpenRLClaimGroupList {
	if in == nil {
		return nil
	}
	out := new(OpenRLClaimGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenRLClaimGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenRLClaimGroupSpec) DeepCopyInto(out *OpenRLClaimGroupSpec) {
	*out = *in
	if in.Seats != nil {
		in, out := &in.Seats, &out.Seats
		*out = make([]Seat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenRLClaimGroupSpec.
func (in *OpenRLClaimGroupSpec) DeepCopy() *OpenRLClaimGroupSpec {
	if in == nil {
		return nil
	}
	out := new(OpenRLClaimGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenRLWorkload) DeepCopyInto(out *OpenRLWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenRLWorkload.
func (in *OpenRLWorkload) DeepCopy() *OpenRLWorkload {
	if in == nil {
		return nil
	}
	out := new(OpenRLWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenRLWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenRLWorkloadList) DeepCopyInto(out *OpenRLWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenRLWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenRLWorkloadList.
func (in *OpenRLWorkloadList) DeepCopy() *OpenRLWorkloadList {
	if in == nil {
		return nil
	}
	out := new(OpenRLWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenRLWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenRLWorkloadSpec) DeepCopyInto(out *OpenRLWorkloadSpec) {
	*out = *in
	in.Accelerator.DeepCopyInto(&out.Accelerator)
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenRLWorkloadSpec.
func (in *OpenRLWorkloadSpec) DeepCopy() *OpenRLWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(OpenRLWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenRLWorkloadStatus) DeepCopyInto(out *OpenRLWorkloadStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenRLWorkloadStatus.
func (in *OpenRLWorkloadStatus) DeepCopy() *OpenRLWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(OpenRLWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Seat) DeepCopyInto(out *Seat) {
	*out = *in
	out.HostRequest = in.HostRequest.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Seat.
func (in *Seat) DeepCopy() *Seat {
	if in == nil {
		return nil
	}
	out := new(Seat)
	in.DeepCopyInto(out)
	return out
}
